# Generated by Django 3.1.6 on 2021-02-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='my_portfolio/img'),
        ),
    ]
